version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=+e$$s(0s$$=i#v3(dtc0xn75(j_9et)0_r!)r$$+s=l1s1d6b&_l3"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:




